export const Keys = {
    CALCULATOR_TEXT_INPUT_FOCUSED: 'CALCULATOR_TEXT_INPUT_FOCUSED',
    CALCULATOR_TEXT_INPUT_UNFOCUSED: 'CALCULATOR_TEXT_INPUT_UNFOCUSED',
    CALCULATOR_DISMISS: 'CALCULATOR_DISMISS',
    CALCULATOR_CALCULATE: 'CALCULATOR_CALCULATE',
    CALCULATOR_HEIGHT_UPDATED: 'CALCULATOR_HEIGHT_UPDATED',
    CALULATOR_PUSH_KEY: 'CALULATOR_PUSH_KEY'
};
